# Generated by Django 4.2.6 on 2023-10-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('is_claimed', models.BooleanField(default=False)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work_order', models.CharField(max_length=100)),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='TimeManagement.workshift')),
            ],
        ),
        migrations.CreateModel(
            name='CompTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_time', models.DateTimeField()),
                ('work_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimeManagement.workshift')),
            ],
        ),
    ]
