# Generated by Django 4.2.6 on 2023-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimeManagement', '0002_alter_workshift_duration_alter_workshift_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
